# Generated by Django 3.2.13 on 2022-05-08 08:30

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('born_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='3251272081', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SC', 'SCIENCTIFIC'), ('AD', 'ADVENTURE'), ('FC', 'FICTION'), ('NFC', 'NON-FICTION')], max_length=10)),
                ('Publications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('library', models.ManyToManyField(related_name='books', to='app.Library')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.publication'),
        ),
    ]
