# Generated by Django 3.2.13 on 2022-05-08 09:07

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='app.publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=app.models.generate_isbn, max_length=10, unique=True),
        ),
    ]
